### ISSUE TITLE
Word integration should be differentiation 

### ISSUE THREAD

**Issue by w-reynolds** [calcmogul/controls-engineering-in-frc#10]
Amazing Book.  Have only read first 16 pages and have already decided this is going to be our reference book for FRC Team 7433.
Think I spotted an typo, could be wrong. Page 16 Section 2.6, Word in bold, integration should be differentiation. As the velocity is the derivative of position, not the integral of position.

If the setpoint follows a trapezoidal motion profile (see chapter 16), tuning becomes a lot easier.
Plot the position setpoint, velocity setpoint, measured position, and measured velocity. The velocity
setpoint can be obtained by numerical **integration** vdes,k =
rk−rk−1
∆t
. Increase Kp until the position
tracks well, then increase Kd until the velocity tracks well.

**Comment by calcmogul** [comment]
Yep. Will push a fix momentarily.

**Comment by calcmogul** [comment]
Thanks for the report. :) Glad you find the book useful.
