### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Zentrik** [calcmogul/controls-engineering-in-frc#14]
https://github.com/calcmogul/controls-engineering-in-frc/blob/f13e5d00c467f50d2292d9daaf2539d1f4eaba11/estimation-and-localization/stochastic-control-theory/introduction-to-probability.tex#L94
I think this should be `Let $x$ and $y$ be`
https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/modern-control-theory/ss-applications/flywheel.tex#L171
also not alsa
https://github.com/calcmogul/controls-engineering-in-frc/blob/f13e5d00c467f50d2292d9daaf2539d1f4eaba11/estimation-and-localization/stochastic-control-theory/linear-stochastic-systems.tex#L22
`$E[\mat{v}_k\mat{v}_j^T] = 0$`

https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/two-sensor-problem.tex#L30-L31
https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/two-sensor-problem.tex#L40-L41
The LHS of both lines seems to be the same even though the RHS is different.

I think lines 30-31 should be
```
w_1 &= \lim_{\sigma_0^2 \to \inf} \frac{\sigma_0^2}{\sigma_0^2 + \sigma^2} = 1 \\ 
w_2 &= \lim_{\sigma_0^2 \to \inf} \frac{\sigma^2}{\sigma_0^2 + \sigma^2} = 0 
```

And 40-41:
```
w_1 &= \lim_{\sigma_0^2 \to 0} \frac{\sigma_0^2}{\sigma_0^2 + \sigma^2} = 0 \\ 
w_2 &= \lim_{\sigma_0^2 \to 0} \frac{\sigma^2}{\sigma_0^2 + \sigma^2} = 1 
```

https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/kalman-filter.tex#L99

I'm not sure but is this meant to be `$\mat{x}_{k+1} - \hat{\mat{x}}_{k+1}^+$`

https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/kalman-filter.tex#L156
S is sort of randomly introduced with no explanation.

https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/kalman-filter.tex#L159
Similarly, the trace is introduced I believe without explaining what it is. It could be introduced in 4.9. 

Also in subsection 6.5, you may want to link to 3blue1brown's matrix exponential video.

https://github.com/calcmogul/controls-engineering-in-frc/blob/b6e5148a3818a20618d11b18344a8cdda043fdf0/estimation-and-localization/stochastic-control-theory/kalman-filter.tex#L225

Not sure but maybe `\subsubsection{Simplified \textit{a posteriori} estimate covariance update equation}`

https://github.com/calcmogul/controls-engineering-in-frc/blob/f13e5d00c467f50d2292d9daaf2539d1f4eaba11/README.md#L11-L12
and provide a lower barrier to entry to the field. Or and lower the barrier to entry to the field. 

https://github.com/calcmogul/controls-engineering-in-frc/blob/f13e5d00c467f50d2292d9daaf2539d1f4eaba11/estimation-and-localization/pose-estimation/pose-exponential.tex#L378
I think this is supposed to be v_x

**Comment by calcmogul** [comment]
Thanks for the thorough comments! All of them are valid. Could you review the linked PR to confirm all of your comments have been addressed? By the way, I added the 3b1b video link earlier today. :slightly_smiling_face:
