### ISSUE TITLE
Links and table of content seem broken (related to Ghostscript version 9.56.0 and above)

### ISSUE THREAD

**Issue by Vincent-Stragier** [calcmogul/controls-engineering-in-frc#17]
Hello @calcmogul,

When opening the [latest version](https://github.com/calcmogul/controls-engineering-in-frc/commit/19e76ec) of the book, I see the following in the page selector:
![image](https://user-images.githubusercontent.com/28227183/163779623-56f9c47c-f3b0-48b2-a2da-287985880a6d.png)

In a [previous version](https://github.com/calcmogul/controls-engineering-in-frc/commit/598eee4), I could see that:
![image](https://user-images.githubusercontent.com/28227183/163779864-71d4350a-6a60-4a9f-b495-427d71ce08db.png)

And the table of content was present (it's empty in the latest version):
![image](https://user-images.githubusercontent.com/28227183/163780151-023fe99c-78cc-4d10-8610-3ccc99255b8a.png)

I rapidly looked at the [changes](https://github.com/calcmogul/controls-engineering-in-frc/compare/598eee4...19e76ec), but I could not find the origin of the bug.

**Comment by calcmogul** [comment]
A recent version of Ghostscript seems to be causing the issue because the uncompressed PDF looks fine.
