### ISSUE TITLE
Why x not y

### ISSUE THREAD

**Issue by SpencerGreene** [calcmogul/controls-engineering-in-frc#19]

**Comment by SpencerGreene** [comment]
Maybe a dumb question but in the PID section:
https://github.com/calcmogul/controls-engineering-in-frc/blob/a76d9d7c5e4cfd653ee5640d5ee1e3a27c71cf87/fundamentals-of-control-theory/pid-controllers/derivative-term.tex#L62
the expansion is shown as e(k) = r(k) - x(k).  Why isn't it e(k) = r(k) - y(k)?  The spring equation uses x but the control system example and diagram use y, am I missing something?

**Comment by calcmogul** [comment]
The state and output of the PID controller are equivalent in this context, but I'll modify it to use y for consistency.
