### ISSUE TITLE
Missing joint PDF term for expected value integral in section 9.3.4

### ISSUE THREAD

**Issue by D3rpyDolphin** [calcmogul/controls-engineering-in-frc#20]
Here is a screenshot of what I believe is incorrect on page 130:
![image](https://user-images.githubusercontent.com/20031686/205430115-a1318202-ed95-449b-bef7-96c41d7c6fe1.png)
Those expected values should include a p(x,y) term within the integral.

**Comment by calcmogul** [comment]
Yep, good catch.
