### ISSUE TITLE
possible typo on page 59

### ISSUE THREAD

**Issue by narmstro2020** [calcmogul/controls-engineering-in-frc#22]
In section 6.9.3 you have the equation

Buff = mg.  

I think it should be Buff = g

I did some checking in the simulator with values and determined for our elevator a mass specific mass.  When solving for it using this equation I found that an extra square root occurred.  If I'm not mistaken B has units of (m/s^2)  / volt.  The right hand side should be the same.

**Comment by calcmogul** [comment]
Yep, Bu_ff has units of acceleration, so the right-hand side should be the acceleration due to gravity g.
